import type { Difficulty, Question } from '../adaptive';
import type { Curriculum } from './curriculum';

export const QUESTION_LIMITS = {
  question: { min: 5, max: 500 },
  option: { max: 200 },
  options: { min: 2, max: 6 },
} as const;

export interface QuestionDraft {
  concept: string;
  difficulty: Difficulty;
  question: string;
  options: string[];
  correctAnswer: string;
  misconceptionMap: Record<string, string>;
}

export type QuestionField = 'concept' | 'question' | 'options' | 'correctAnswer' | 'misconceptionMap';

export interface QuestionIssue {
  field: QuestionField;
  message: string;
}

/** Comparable form of question text: case, spacing, and trailing punctuation do not matter. */
export function normalizeQuestionText(text: string): string {
  return text.toLowerCase().replace(/\s+/g, ' ').replace(/[\s.?!:]+$/, '').trim();
}

interface ValidationContext {
  curriculum: Pick<Curriculum, 'concept' | 'misconception'>;
  existing: Question[];
  /** The question being edited, so it is not reported as a duplicate of itself. */
  ignoreId?: string;
  /** Misconceptions that will be created together with the question. */
  pendingMisconceptionIds?: ReadonlySet<string>;
}

/**
 * One set of rules for every question that enters a learner's bank, whether written by hand or
 * generated by AI. Mirrors the server's validation of curated questions.
 */
export function validateQuestion(draft: QuestionDraft, context: ValidationContext): QuestionIssue[] {
  const issues: QuestionIssue[] = [];
  const add = (field: QuestionField, message: string) => issues.push({ field, message });

  if (!context.curriculum.concept(draft.concept)) add('concept', 'Choose a topic.');

  const text = draft.question.trim();
  if (text.length < QUESTION_LIMITS.question.min || text.length > QUESTION_LIMITS.question.max) {
    add('question', `Write a question of ${QUESTION_LIMITS.question.min}–${QUESTION_LIMITS.question.max} characters.`);
  } else {
    const normalized = normalizeQuestionText(text);
    const duplicate = context.existing.some((item) => item.id !== context.ignoreId
      && item.concept === draft.concept && normalizeQuestionText(item.question) === normalized);
    if (duplicate) add('question', 'This topic already has a question with the same wording.');
  }

  const options = draft.options.map((option) => option.trim());
  if (options.length < QUESTION_LIMITS.options.min || options.length > QUESTION_LIMITS.options.max) {
    add('options', `Give ${QUESTION_LIMITS.options.min}–${QUESTION_LIMITS.options.max} options.`);
  } else if (options.some((option) => !option)) {
    add('options', 'Fill in every option or remove the empty ones.');
  } else if (options.some((option) => option.length > QUESTION_LIMITS.option.max)) {
    add('options', `Keep each option under ${QUESTION_LIMITS.option.max} characters.`);
  } else if (new Set(options.map((option) => option.toLowerCase())).size !== options.length) {
    add('options', 'Options must be different from each other.');
  }

  const correct = draft.correctAnswer.trim();
  if (!options.includes(correct)) add('correctAnswer', 'The correct answer must be one of the options.');

  Object.entries(draft.misconceptionMap).forEach(([option, id]) => {
    if (!options.includes(option.trim()) || option.trim() === correct) {
      add('misconceptionMap', `“${option}” is not one of the wrong options.`);
    } else if (!context.curriculum.misconception(id) && !context.pendingMisconceptionIds?.has(id)) {
      add('misconceptionMap', `Unknown misconception “${id}”.`);
    }
  });

  return issues;
}
